import { DigitKeySchema, FunctionKeySchema, LetterKeySchema, NumpadKeySchema } from '../schemas/command'

type NonModifierKeySchema = LetterKeySchema | FunctionKeySchema | DigitKeySchema | NumpadKeySchema

type KeyboardEventFieldSchema = 'key' | 'code'

export const keyboardEventMapping: Record<NonModifierKeySchema, KeyboardEventFieldSchema> = {
  A: 'key',
  B: 'key',
  C: 'key',
  D: 'key',
  E: 'key',
  F: 'key',
  G: 'key',
  H: 'key',
  I: 'key',
  J: 'key',
  K: 'key',
  L: 'key',
  M: 'key',
  N: 'key',
  O: 'key',
  P: 'key',
  Q: 'key',
  R: 'key',
  S: 'key',
  T: 'key',
  U: 'key',
  V: 'key',
  W: 'key',
  X: 'key',
  Y: 'key',
  Z: 'key',
  F1: 'key',
  F2: 'key',
  F3: 'key',
  F4: 'key',
  F5: 'key',
  F6: 'key',
  F7: 'key',
  F8: 'key',
  F9: 'key',
  F10: 'key',
  F11: 'key',
  F12: 'key',
  Digit0: 'code',
  Digit1: 'code',
  Digit2: 'code',
  Digit3: 'code',
  Digit4: 'code',
  Digit5: 'code',
  Digit6: 'code',
  Digit7: 'code',
  Digit8: 'code',
  Digit9: 'code',
  Numpad0: 'code',
  Numpad1: 'code',
  Numpad2: 'code',
  Numpad3: 'code',
  Numpad4: 'code',
  Numpad5: 'code',
  Numpad6: 'code',
  Numpad7: 'code',
  Numpad8: 'code',
  Numpad9: 'code',
}
